org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Parchment mappings (NeoGradle subsystem). See https://parchmentmc.org/docs/getting-started
neogradle.subsystems.parchment.minecraftVersion=1.20.2
neogradle.subsystems.parchment.mappingsVersion=2023.12.10

minecraft_version=1.20.2
minecraft_version_range=[1.20,1.21)
neo_version=20.2.93
neo_version_range=[20.2,)
loader_version_range=[1,)

mod_id=alchemistry
mod_name=Alchemistry
mod_license=LGPLv2.1
mod_version=2.4.1
mod_group_id=com.smashingmods.alchemistry
mod_authors=DarkArcana
mod_description=Alchemistry is a tech mod, inspired by the classic Minechem, that allows you to decompose items into their constituent elements, then recombine them to create new items.

chemlib_version=2.1.1
alchemylib_version=1.1.1
jei_version=16.0.0.28
