modLoader="javafml"
loaderVersion="${loader_version_range}"
license="LGPLv2.1"
issueTrackerURL="https://github.com/TonimatasDEV/Alchemistry/issues"

[[mods]]
modId="alchemistry"
version="${modVersion}"
displayName="Alchemistry"
logoFile="alchemistry-logo.png"
authors="DarkArcana - Creator | TonimatasDEV - Port"
description='''
Alchemistry is a tech mod, inspired by the classic Minechem, that allows you to decompose items into their constituent elements, then recombine them to create new items.
'''

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.alchemistry]]
modId="neoforge"
required=true
versionRange="${neoforgeVersionRange}"
ordering="NONE"
side="BOTH"

[[dependencies.alchemistry]]
modId="minecraft"
required=true
versionRange="[${minecraftVersion}]"
ordering="NONE"
side="BOTH"

[[dependencies.alchemistry]]
modId="chemlib"
required=true
versionRange="${chemlibVersionRange}"
ordering="NONE"
side="BOTH"

[[dependencies.alchemistry]]
modId="alchemylib"
required=true
versionRange="${alchemylibVersionRange}"
ordering="NONE"
side="BOTH"
