@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.smashingmods.alchemistry.api.storage;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;