@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.smashingmods.alchemistry.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;