@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.smashingmods.alchemistry.common.recipe.fission;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;