modLoader="javafml"
loaderVersion="[1,)"
license="LGPLv2.1"
issueTrackerURL="https://github.com/TonimatasDEV/Alchemistry/issues"

[[mods]]
modId="alchemistry"
version="2.3.4"
displayName="Alchemistry"
logoFile="alchemistry-logo.png"
authors="DarkArcana - Creator | TonimatasDEV - Port"
description='''
Alchemistry is a tech mod, inspired by the classic Minechem, that allows you to decompose items into their constituent elements, then recombine them to create new items.
'''

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.alchemistry]]
modId="neoforge"
required=true
versionRange="[21,22)"
ordering="NONE"
side="BOTH"

[[dependencies.alchemistry]]
modId="minecraft"
required=true
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.alchemistry]]
modId="chemlib"
required=true
versionRange="[2.0,2.1)"
ordering="NONE"
side="BOTH"

[[dependencies.alchemistry]]
modId="alchemylib"
required=true
versionRange="[1.0,2.0)"
ordering="NONE"
side="BOTH"
