@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.smashingmods.alchemistry.api.blockentity.handler;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;